### ISSUE TITLE
`belief` or `update_belief`

### ISSUE THREAD

**Issue by zsunberg** [sisl/POMDPs.jl#26]
As I was doing the getting rid of! refactor, I noticed this.

`update_belief` is now similar to `transition`, `observation`, etc. Why should it be named differently (with update at the beginning)? One potential reason is that the object to be modified may be passed in as the second argument in addition to its place as the final argument. I went ahead and changed it to `belief`, but we could keep it as `update_belief`. What do y'all think?

Also, the current setup could get a little weird because the problem-programmer might assume that bold and belief are different objects and might do calculations in a way that doesn't function correctly if both are pointing to the same object. Is this ok?

**Comment by zsunberg** [comment]
@ebalaban, earlier today I think you said that you thought we had reached consensus about the possibility of adding a BeliefUpdater. After thinking about it some more, I really think introducing that will be more of a hassle than it's worth. Can we open a new issue to discuss that?

**Comment by zsunberg** [comment]
I think the main original questions in this issue have been addressed, but before closing it, I think there is one thing that I would like to clarify: Can we make the following demand?

`belief()` should *not* modify the `belief_old` argument.

POMCP, for example, currently relies on this assumption to keep from making a bunch of calls to deepcopy. Alternatively, is there a way that I can efficiently check (@assert) that this belief has not been modified without requiring someone else to define the == operator?

**Comment by ebalaban** [comment]
@zsunberg, sorry for the confusion, I think I had particle data types in POMDPToolbox in mind as the issue that we've converged on. Anyway, I do feel pretty strongly that a BeliefUpdater type is needed, so I am looking forward to a lively discussion :-) I'll open a separate issue on this.

**Comment by zsunberg** [comment]
I think at some point, we should clarify what `belief` (now `update`) can do with its arguments, but this issue is stale, so I'm closing it.
