### ISSUE TITLE
Interface Changes

### ISSUE THREAD

**Issue by zsunberg** [sisl/POMDPs.jl#35]
This issue will be a central place to discuss implementation of the changes decided on in our October 2nd in-person meeting. This should fix #32, #33, and #34

I created a branch (b43ecf8462a881f5046dad3975733eeec69d49b9), but the only changes I have made so far are to the README. I have changed the format somewhat (if we don't like this I'm fine with going back).

First big question: Should I continue with this branch, or just start pushing straight to master?

**Comment by ebalaban** [comment]
A branch is probably a good idea, so that we can experiment a bit and see what works/looks right.

**Comment by zsunberg** [comment]
I think I have implemented all of the changes in the branch. Testing it and documenting it will still take some time.

**Comment by ebalaban** [comment]
@zsunberg, thanks for implementing this. Looks good so far overall. I would, however, like to see the second argument put back into initial_belief (as in initial_belief(pomdp::POMDP, belief::Belief)). This serves a dual purpose: allows the initial belief to be filled into a pre-allocated belief structure (created with, perhaps, create_belief) and allows to elegantly dispatch creation of initial belief in different forms, if the problem writer would like to provide that. I would also still like to see a create_belief(pomdp::POMDP) function that creates an empty belief structure in the default problem-native format. Here is an example of how it would all work:

```julia

######### On the solver/belief updater side: #########

# The only difference from the regular ParticleBelief (problem-native format) is that
# in this case is that we maintain history here as well
type DESPOTBelief{T} <: Belief
    particles::Vector{Particle{T}}
    history::History
end

# Special create_belief version for DESPOTBeliefUpdater
function create_belief(bu::DESPOTBeliefUpdater)
    particles = Array(Particle{bu.state_type},0)
    history = History()
    belief = DESPOTBelief{bu.state_type}(particles, history)
    return belief
end

######### On the problem side: #########

# Creates a default belief structure to store the problem's initial belief
function create_belief(pomdp::RockSample)
    return ParticleBelief{RockSampleState}(Array(Particle{RockSampleState},0))
end

# Generic initial belief. 
# Calling without the second argument would allocate memory for belief here.
function initial_belief(pomdp::RockSample,
                        belief::ParticleBelief{RockSampleState} = create_belief(pomdp))
    fill_initial_belief_particles!(pomdp, belief.particles)
    return belief
end

# special initial_belief for the DESPOTBelief format
function initial_belief(pomdp::RockSample, belief::DESPOT.DESPOTBelief{RockSampleState})
    fill_initial_belief_particles!(pomdp, belief.particles)
    return belief
end

function fill_initial_belief_particles!(pomdp::RockSample, particles::Vector{Particle{RockSampleState}})
    # fill in the particles here
end

########## On the 'experimenter' side ############
pomdp  = RockSample(grid_size, num_rocks)
bu = DESPOTBeliefUpdater(pomdp::POMDP))
current_belief = create_belief(bu)
initial_belief(pomdp, current_belief)

```

If there are no objections, I can make the changes.

**Comment by zsunberg** [comment]
Ok, I suppose this would be useful in some cases. Was this one of the
things we talked about in the meeting? I realized I didn't write the things
down, so perhaps I forgot it.

**Comment by zsunberg** [comment]
In the `create_belief` function above, should the native belief type returned by `create_belief(::RockSample)` always be a particle belief? I was envisioning that the default domain-specific belief would usually, if not always be an exact belief.

**Comment by ebalaban** [comment]
@zsunberg , in response to your first comment, I thought we discussed the dual-argument initial_belief() issue at some length at the meeting (it was also the subject of #33). As for create_belief(::POMDP), I realized that we may want to preserve it as I was coding things up and saw that it would be useful for the default initial_belief() version.

I think that the problem-native belief type should be up to the problem writers. Particles work for me in the RockSample case, but others may chose different representations. Some of them will surely be exact, but personally I don't think that an exact belief will work for every problem.

**Comment by zsunberg** [comment]
Yeah, I think we did discuss it - sorry for forgetting to implement it!

**Comment by ebalaban** [comment]
Oh, no worries, there were a lot of things discussed during the meeting. Are you ok with create_belief(::POMDP) as well? We could consider changing the name too, to better differentiate from create_belief(::BeliefUpdater).

**Comment by zsunberg** [comment]
I think inclusion of `create_belief(::POMDP)` is just a style choice. I would vote against it because I don't believe it's not strictly needed anywhere. I think the two approaches below result in the same functionality:

Here are the function definitions that I propose:
```julia
initial_belief(::POMDP) # convenience function that returns a reasonable initial belief for the problem
initial_belief(::POMDP, b::Belief) # convenience function that fills b with a reasonable initial belief for the problem and returns it
```

The other option is to do exactly what you said, i.e. the initial belief and create belief signatures are
```julia
initial_belief(pomdp::POMDP, b::Belief=create_belief(pomdp)) # convenience function that fills b with a reasonable initial belief for the problem and returns it
create_belief(::POMDP) # creates a domain-specific belief representation
```

Again, I'd vote for the first, but I am ok with the second.

**Comment by ebalaban** [comment]
I considered your first option as well, but then decided that the second option would be a bit more consistent with our larger philosophy of pre-allocating objects through create_* functions whenever possible and passing them into other functions that populate/modify them.

In this case, however, it is indeed mostly a stylistic difference. At the moment I can't think of b = create_belief(::POMDP) being used for a purpose other than passing the empty b immediately into initial_belief() (unless one needs to find out what the problem-native belief type is, for some reason). I am fine with the first option if you prefer it strongly. If others have an opinion one way or another, please let us know.

**Comment by goretkin** [comment]
Sorry to join the discussion late. [Convention](http://julia.readthedocs.org/en/latest/stdlib/base/) in Julia Base (and many packages) would have `initial_belief(::POMDP, b::Belief)` actually called `initial_belief!(::POMDP, b::Belief)`

> By convention, function names ending with an exclamation point (!) modify their arguments. Some functions have both modifying (e.g., sort!) and non-modifying (sort) versions.

**Comment by zsunberg** [comment]
Hi @goretkin, thanks for the comment! We were aware of this convention, however we decided to depart from it for some functions in the interface when the last argument is an optional pre-allocated object (see #23).

**Comment by zsunberg** [comment]
@mykelk , @etotheipluspi any preferences on the two options for initial belief above?

**Comment by zsunberg** [comment]
FYI all, I have created `policy_specific_belief` branches in POMDPModels and POMDPToolbox for this that will be merged into those packages when we merge this in.

**Comment by etotheipluspi** [comment]
@zsunberg I like the first option. Reducing the number of function names seems like a good idea.

**Comment by mykelk** [comment]
@zsunberg I vote for the second option. Although I do like reducing the number of function names like @etotheipluspi, the data structure for a belief might be complex and something that we might not want to reallocate every time. We might want to reset to the initial belief multiple times in a loop, and we might want to avoid reallocating every time.

**Comment by etotheipluspi** [comment]
@mykelk I might be misunderstanding @zsunberg , but it seems like we can call 
```julia 
initial_belief(::POMDP, b::Belief) 
``` 
to avoid allocating belief many times. The belief data structure can be pre-allocated by calling ```b = initial_belief(::POMDP)```

**Comment by mykelk** [comment]
@etotheipluspi you're right. I misunderstood. In that case, the argument for the second might be that we have create_ for all the other complex objects. But, I'm fine either way this goes.

**Comment by ebalaban** [comment]
Hm, Max (@etotheipluspi), that's not quite what we had in mind... Under Option 1, b = initial_belief(::POMDP) would allocate, fill, and return a problem-native belief structure (e.g., a set of particles). So, for Mykel's example, if repeated calls to initial_belief are required, new memory is allocated each time. initial_belief(::POMDP, b::Belief) is used to get the initial belief in a belief-updater/solver format, dispatched by the Belief type (e.g. a Gaussian). So, if we wanted to avoid repeated memory allocation in Mykel's scenario **and** wanted to use problem-native belief representation throughout, then we are better off with Option 2, which provides a create_belief(::POMDP) function that returns an empty structure in the problem-native format.

**Comment by etotheipluspi** [comment]
@ebalaban I am still a bit confused here. It seems like we want two things:
1) Initialize the problem side belief
2) Convert the problem belief to the solver belief

I now see that my post above is not correct, but I don't see why approach two allows you to avoid allocating memory. In both cases, ```initial_belief(::POMDP, b::Belief)``` needs to convert the problem belief b to the solver belief, requiring memory allocation. Unless ```initial_belief()``` is overloaded to fill both problem belief and solver belief, which I think can be done for both approaches.

**Comment by ebalaban** [comment]
@etotheipluspi, yes, initial_belief(::POMDP, b::Belief) would be overloaded to fill either problem belief or solver belief, depending on the call signature. The main difference between Option 1 and Option 2 is that in the latter create_belief(::POMDP) would be available to pre-allocate memory outside of initial_belief(::POMDP, b::Belief) and in the former that memory is allocated inside initial_belief(::POMDP), which is a function that's **only** used for getting problem-native initial belief. A separate two-argument initial_belief(::POMDP, b::Belief) function would be used to get solver-native belief (no explicit belief conversion takes place there).

**Comment by zsunberg** [comment]
I don't think `create_belief(::POMDP)` would be super useful for allocating beliefs outside of `initial_belief` because, in order to fill the belief with data, the experimenter or solver writer using `create_belief(::POMDP)` would have to know details about the structure of the belief, so it would require little extra effort to create the specific belief object they want manually. In other words, since we don't have a generic way to fill a belief besides `initial_belief`, we don't really need a generic allocator. That being said, I still think either solution is fine - my very weak preference would be for the first.

Anyways, we should just pick one and go with it - the cost of choosing the wrong one is lower than the cost of delaying more I think :)

**Comment by ebalaban** [comment]
Agreed, although create_belief(::POMDP) does help in the scenario that @mykelk described. @etotheipluspi and I talked today in person and I think we've cleared up any remaining misunderstandings. I'll go ahead and implement Option 2, since I think it is closer to our general pattern and provides a bit more flexibility.

**Comment by zsunberg** [comment]
Sounds good

**Comment by zsunberg** [comment]
Max and I talked about this earlier today and I think we are going to try to merge the branch into master this weekend. I have tested it with the crying baby problem. I will update the readme with function descriptions today or tomorrow. Anybody have any concerns?

**Comment by ebalaban** [comment]
Sounds good to me. I've been using this branch as well with RockSample. The one issue I've been meaning to revisit is #25, but I'll comment in that thread separately.

**Comment by zsunberg** [comment]
I opened a pull request #39 to merge this in. @etotheipluspi , please merge it in as soon as you get a chance

**Comment by zsunberg** [comment]
@etotheipluspi , did you have a chance to look at merging the branch in? Did you run into any problems?

**Comment by etotheipluspi** [comment]
@zsunberg branch has been merged. Everything works on my end. Thanks for waiting.
