### ISSUE TITLE
Macro to automatically generate error messages for interface functions

### ISSUE THREAD

**Issue by zsunberg** [sisl/POMDPs.jl#37]
Hi all, I am working on a macro that will automatically generate the error messages for the functions in the interface. I talked to Max about this yesterday, and I think it will be pretty useful.

Instead of
```julia
create_state(pomdp::POMDP) = error("$(typeof(pomdp)) does not implement create_state")
```

We'll just be able to type
```julia
@pomdp_func create_state(pomdp::POMDP)
```

or something similar in the source and it will automatically generate the default error implementation. I think this will help us be more consistent and correct, and if we want to change the way these errors show up we can do it all from one place.

I don't really think pomdp_func is a great name - if anyone has any ideas, let me know.

**Comment by zsunberg** [comment]
Does anyone have a big problem with this? If you do, please speak now. I am planning on using this everywhere in the policy_specific_belief branch, and I'd rather not have to convert back to the old way

**Comment by ebalaban** [comment]
How are you planning to handle the more-descriptive message styles of #31? Wouldn't it be a little hard to come up with a macro (or macros) to generate meaningful messages for multi-argument functions?

**Comment by zsunberg** [comment]
Actually, that's one of the big reasons I'm doing this - it's easier and
more accurate to do it programmatically than by hand

**Comment by mykelk** [comment]
That's fine.

**Comment by ebalaban** [comment]
Ok, if you think this will make life easier, I am all for it.

**Comment by zsunberg** [comment]
This is implemented, check it out in the policy_specific_belief branch if you're curious to see how it looks
