### ISSUE TITLE
Tiger example

### ISSUE THREAD

**Issue by sheromon** [sisl/POMDPs.jl#41]
The readme for POMDPs.jl has links to two examples, grid world for MDPs and the tiger problem for POMDPs. But the link to the tiger problem goes nowhere? I looked the "examples" folder as well and found grid world but no tiger problem.

**Comment by etotheipluspi** [comment]
It's been updated! Thanks for waiting. The tutorial gives a brief overview of implementing the tiger problem using the POMDPs.jl interface, and shows you how to use QMDP and SARSOP solvers.

Good luck, and feel free to contact me if you run into any problems!

**Comment by sheromon** [comment]
Hey, thanks for the great response time!
