### ISSUE TITLE
FYI: POMCP is ready for public consumption/improvement

### ISSUE THREAD

**Issue by zsunberg** [sisl/POMDPs.jl#42]
Hey all,

Didn't know how to notify interested people about this in any way other than creating an issue. FYI I added POMCP to the list of solvers. It's pretty bare-bones right now, and probably pretty slow compared to what it could be, but it's ready for initial consumption if AA228ers want to use it or help me improve it.

I'll be adding features as I use it more.

**Comment by zsunberg** [comment]
Maybe we should create a pomdps-users listserve for stuff like this and people who want to ask for help

**Comment by etotheipluspi** [comment]
+1 for adding a listserve. 

Awesome addition to the solver suite! I'll be trying it out this weekend.

**Comment by mykelk** [comment]
I think creating a Google groups (as done for julia-users) would be good.

**Comment by mykelk** [comment]
I can take that action, if others agree.

**Comment by ebalaban** [comment]
I like the idea.

**Comment by mykelk** [comment]
Created group [here](https://groups.google.com/forum/#!forum/pomdps-users). Feel free to subscribe and then I'll add you as an owner.
