### ISSUE TITLE
POMDP Tutorial link broken

### ISSUE THREAD

**Issue by zsunberg** [sisl/POMDPs.jl#43]
The POMDP Tutorial link in the README is not working for me.

The browser says:

400 : Bad Request
We couldn't render your notebook
Perhaps it is not valid JSON, or not the right URL.
If this should be a working notebook, please let us know.
The error was: HTTP 403: Forbidden

I am logged into github, so it seems that I don't have the proper credentials on ipython.org

**Comment by mykelk** [comment]
It seems to work for me.

**Comment by zsunberg** [comment]
Works now for me as well. Guess the problem was on their side.
