### ISSUE TITLE
current function signature for action is invalid

### ISSUE THREAD

**Issue by zsunberg** [sisl/POMDPs.jl#44]
The current function signature for action is
```julia
action(p::Policy, state::State, action=create_action(pomdp))
```
This is not valid because `pomdp`, the argument to `create_actions`, is not one of the arguments of `action`.

How should we fix this? If a policy is required to be able to specify an action given the state, then we a `create_action(::Policy)` method makes sense. I think that's the best option. What do y'all think?

**Comment by mykelk** [comment]
I think actions are a property of the POMDP. So, it seems to make sense to keep `create_action(pomdp)`. Maybe just keep it
```julia
action(p::Policy, state::State)
action(p::Policy, state::State, action::Action)
```
and let the implementer of the policy handle it---probably by accessing a reference to the POMDP object it squirreled away in the policy object.

**Comment by zsunberg** [comment]
Yeah, that seems like a good way to do it.

**Comment by ebalaban** [comment]
Agreed.

**Comment by zsunberg** [comment]
Any objections? If not, I'll make the change.

**Comment by etotheipluspi** [comment]
Sounds good to me.
