### ISSUE TITLE
random states (perhaps actions and observations as well)

### ISSUE THREAD

**Issue by ebalaban** [sisl/POMDPs.jl#49]
Here is another issue that came up for me. In order to refill an empty particle filter, I'd like to randomly sample states. State creation should, obviously, happen on the problem side. Given our current interface, I don't see a clean way of generating a random state, but here are a couple of options that come to mind:

1. Use rand!(). This is my preferred option, but the only two distribution types currently supported through the interface are transition distributions and observation distributions. We could, for example, add create_state_distribution() that would return an AbstractDistribution that can then be immediately used in rand!(). I can also see the same being useful for actions and observations down the road.

2. Have create_state() and alike return a random state rather than some arbitrary/empty/invalid state. Given their current form, we would not be able to pass an RNG into create_* functions though and this option also takes us away from our philosophy of create_* functions serving pre-allocation purposes only.

Can anybody propose something better/easier that I am overlooking?

**Comment by zsunberg** [comment]
Isn't this what `rand!(rng, ::State, ::AbstractSpace)` is for?

**Comment by ebalaban** [comment]
Ah, that'll work. I wasn't aware (or perhaps forgot) that we already have something like this, should have looked through the code more carefully. It's not listed in the README, either explicitly or implicitly. I'll update the docs and then close the issue. Sorry for the false alarm.

**Comment by ebalaban** [comment]
I updated README.md with this and other functions that were not yet in it. By the way, I presumed that
```julia
states(pomdp::POMDP, state::State, sts::AbstractSpace=states(pomdp))
```
is for getting the subspace of states accessible from some given state. If that's not the case, please edit.
