### ISSUE TITLE
Space/distribution dimensions

### ISSUE THREAD

**Issue by etotheipluspi** [sisl/POMDPs.jl#50]
I am working on wrapping the MCVI code in C, and I would like to access the dimensions of the state space. Can we have something like:

```julia
dims(space::AbstractSpace)
```

for spaces and maybe for distributions? 

I really only need the number of state variables in the state space for MCVI so maybe we can get around creating a new method. I can get around this by having the user pass in the number of dimensions in the state space into the solver as well.

What does everyone think?

**Comment by ebalaban** [comment]
There is already dimensions(s::AbstractSpace) that is supposed to return 
the number of dimensions. Is that what you need?

**Comment by ebalaban** [comment]
Incidentally, I just put a descriptor for it in the README... :-)

**Comment by etotheipluspi** [comment]
You're right! Thanks for adding the description. I'll close the issue.
