### ISSUE TITLE
Can't put unregistered POMDP packages in REQUIRE -> can't pass Travis

### ISSUE THREAD

**Issue by tawheeler** [sisl/POMDPs.jl#55]
I rigged POMDPSolve with Travis and Coveralls.
When Travis runs, it automatically downloads all dependencies listed in REQUIRE. Unfortunately, our dependencies are not registered packages (you have to clone them), so they aren't recognized in the REQUIRE file and Travis fails.

**Comment by mykelk** [comment]
Yeah, they should be taken out of require for now. You can add commands to the Travis script to clone the necessary packages.

**Comment by tawheeler** [comment]
Smart!
