### ISSUE TITLE
Adding solvers

### ISSUE THREAD

**Issue by mykelk** [sisl/POMDPs.jl#57]
We'll want to register POMDPs.jl as an official package on METADATA.jl, but we probably don't want to litter METADATA with a dozen or so solvers. What if we just register POMDPs.jl and provide a function like POMDPs.add("MCVI"), kind of like Pkg.add, and it will do the necessary cloning?

**Comment by ebalaban** [comment]
Good idea.

**Comment by etotheipluspi** [comment]
I like that as well. This will also allow us to do the builds for solver like SARSOP without the user have to run ```Pkg.build```.

**Comment by etotheipluspi** [comment]
This has been added. You can now run:

```julia
using POMDPs
POMDPs.add("SARSOP")
```
The function will clone and build the solver. The docs have been updated to reflect this.
